server:
  port: 8000
  charset: UTF-8
debug: false
spring:
  mail:
    host: smtp.163.com
    username: ipnet2018@163.com
    password: ipnet2018
    default-encoding: UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/ipnet?characterEncoding=UTF-8&useSSL=true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true
  aop:
    auto: true
constant:
  codeLength: 6